security:
    providers:
        in_memory: { memory: ~ }
        user:
            id: user_provider

    encoders:
      App\Entity\Account: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_login:
            pattern: ^/api/connexion
            anonymous: true
            stateless: true
            provider: user
            guard:
                authenticators:
                    - plugin.id_authentificator

        api:
            pattern: ^/api
            anonymous: false
            provider: user
            guard:
                authenticators:
                    - plugin.token_authenticator

        main:
            pattern: ^/
            anonymous: ~
            provider: user
            logout:
                path: /profile/logout
                target: /profile/login
            guard:
                authenticators:
                    - app.id_authentificator

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    access_control:
         - { path: ^/profile/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/profile/siteInscription, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/profile, roles: ROLE_USER }