security:
    providers:
        in_memory: { memory: ~ }
        user:
            id: user_provider

    encoders:
      App\Entity\Account: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: ~
            provider: user
            logout:
                path: /profile/logout
                target: /profile/login
            guard:
                authenticators:
                    - app.id_authentificator
            access_denied_handler: App\Security\AccessDeniedHandler


    role_hierarchy:
        ROLE_MODERATOR: ROLE_USER
        ROLE_ADMIN: [ROLE_MODERATOR, ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_MODERATOR, ROLE_USER]

    access_control:
         - { path: ^/admin/adherent/update_state, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/profile/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/profile/siteInscription, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/profile/forgotPassword, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/profile/resetPassword/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/admin/activities, roles: ROLE_MODERATOR }
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/profile, roles: ROLE_USER }
