security:
    providers:
        in_memory: { memory: ~ }
        user:
            id: user_provider

    encoders:
      App\Entity\Account: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: ~
            provider: user
            logout:
                path: /deconnexion
                target: /connexion
            guard:
                authenticators:
                    - app.id_authentificator
            access_denied_handler: App\Security\AccessDeniedHandler


    role_hierarchy:
        ROLE_MODERATOR: ROLE_USER
        ROLE_ADMIN: [ROLE_MODERATOR, ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_MODERATOR, ROLE_USER]

    access_control:
         - { path: ^/admin/adherent/update_state, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/siteinscription, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/motdepasseoublie, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/resetmotdepasse, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/admin/activities/views, roles: ROLE_MODERATOR }
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/, roles: ROLE_USER }
