home:
    path: /profile/Accueil
    controller: App\Controller\HomeController::index

registration:
    path: /profile/Inscription
    controller: App\Controller\RegistrationController::index


### Account routing ###
register_site_index:
    path: /profile/siteInscription
    controller: App\Controller\AccountController::index


### Authentication routing ###
connexion_security:
  path: /profile/login
  controller: App\Controller\SecurityController::login

deconnexion_security:
  path: /profile/logout

### Administration routing ###
administration:
    path: /admin/Administration
    controller: App\Controller\AdministrationController::index

adherent_competiteurs:
  path: /admin/competiteurs
  controller: App\Controller\AdministrationController::competiteurs
  methods: [GET]