home:
    path: /profile/Accueil
    controller: App\Controller\HomeController::index

registration:
    path: /profile/Inscription
    controller: App\Controller\RegistrationController::index


### Account routing ###
account_add:
    path: /profile/siteInscription
    controller: App\Controller\AccountController::add

account_update:
    path: /profile/update
    controller: App\Controller\AccountController::update

account_forgot_password:
    path: /profile/forgotPassword
    controller: App\Controller\AccountController::forgotPassword

account_reset_password:
    path: /profile/resetPassword/{token}
    controller: App\Controller\AccountController::resetPassword

### Event routing ###
event_index:
    path: /profile/events
    controller: App\Controller\EventController::index

event_participate:
    path: /profile/participate/{id}
    controller: App\Controller\EventController::participate

event_participate_infos:
    path: /profile/participate/infos/{id}
    controller: App\Controller\EventController::participateInfo

### Authentication routing ###
security_connexion:
    path: /profile/login
    controller: App\Controller\SecurityController::login

security_deconnexion:
    path: /profile/logout

### Administration routing ###
admin_home:
    path: /admin
    controller: App\Controller\administration\AdministrationController::home

admin_adherent_competiteurs:
    path: /admin/competiteurs
    controller: App\Controller\administration\AdministrationController::competiteurs

admin_adherent_update_state:
    path: /admin/adherent/update_state
    controller: App\Controller\administration\AdministrationController::update_state
    methods: POST

    #--adherents
admin_adherents:
    path: /admin/adherents
    controller: App\Controller\administration\AdminAdherentsController::index

admin_adherentsPDF:
    path: /admin/adherents/pdf/{id}
    controller: App\Controller\administration\AdminAdherentsController::generatePDF
    requirements:
        id: ([0-9]*)

admin_adherentsEdit:
    path: /admin/adherents/edit/{id}
    controller: App\Controller\administration\AdminAdherentsController::edit
    requirements:
        id: ([0-9]*)

admin_adherentsDelete:
    path: /admin/adherents/delete/{id}
    controller: App\Controller\administration\AdminAdherentsController::delete
    requirements:
        id: ([0-9]*)

    #--activities
admin_activities_moderator:
    path: /admin/activities/views
    controller: App\Controller\administration\AdminActivitiesController::index

admin_activities:
    path: /admin/activities
    controller: App\Controller\administration\AdminActivitiesController::index

admin_activityAdd:
    path: /admin/activities/addActivity
    controller: App\Controller\administration\AdminActivitiesController::addActivity

admin_activityEdit:
    path: /admin/activities/editActivity/{id}
    controller: App\Controller\administration\AdminActivitiesController::editActivity

admin_activityDelete:
    path: /admin/activities/deleteActivity/{id}
    controller: App\Controller\administration\AdminActivitiesController::deleteActivity

admin_activityDetails:
    path: /admin/activities/details/{id}
    controller: App\Controller\administration\AdminActivitiesController::details
    requirements:
        id: ([0-9]*)

admin_activityAddAdherentToTimeSlot:
    path: /admin/activities/addToTimeSlot
    controller: App\Controller\administration\AdminActivitiesController::addToTimeSlot

admin_activityDeleteAdherentFromTimeSlot:
  path: /admin/activities/deleteFromTimeSlot/{activityId}/{timeSlotId}/{adherentId}
  controller: App\Controller\administration\AdminActivitiesController::deleteFromTimeSlot
  requirements:
    activityId: ([0-9]*)
    timeSlotId: ([0-9]*)
    adherentId: ([0-9]*)

admin_activityCopyAllEmails:
    path: /admin/activities/activityCopyAllEmails
    controller: App\Controller\administration\AdminActivitiesController::copyAllEmails

admin_activityCopyTimeSlotEmails:
  path: /admin/activities/activityCopyTimeSlotEmails
  controller: App\Controller\administration\AdminActivitiesController::copyTimeSlotEmails


    #--Categories
admin_categories:
    path: /admin/categories
    controller: App\Controller\administration\AdminActivitiesController::index

admin_categoryEdit:
    path: /admin/categories/edit/{id}
    controller: App\Controller\administration\AdminActivitiesController::edit

admin_categoryAdd:
    path: /admin/categories/add
    controller: App\Controller\administration\AdminActivitiesController::add

admin_categoryDelete:
    path: /admin/categories/delete/{id}
    controller: App\Controller\administration\AdminActivitiesController::delete

    #--accounts
admin_accounts:
    path: /admin/accounts
    controller: App\Controller\administration\AdminAccountsController::index

admin_accounts_edit:
    path: /admin/accounts/edit/{id}
    controller: App\Controller\administration\AdminAccountsController::edit
    requirements:
        id: ([0-9]*)

admin_accounts_delete:
    path: /admin/accounts/delete/{id}
    controller: App\Controller\administration\AdminAccountsController::delete
    requirements:
        id: ([0-9]*)

    #--events
admin_events:
    path: /admin/events
    controller: App\Controller\administration\AdminEventsController::index

admin_event_update:
    path: /admin/event/update/{id}
    controller: App\Controller\administration\AdminEventsController::update
    requirements:
        id: ([0-9]*)

admin_event_delete:
    path: /admin/event/delete/{id}
    controller: App\Controller\administration\AdminEventsController::delete
    requirements:
        id: ([0-9]*)

    #--event management
admin_event_manager_index:
    path: /admin/event/manager/{id}
    controller: App\Controller\administration\AdminEventManagerController::index
    requirements:
        id: ([0-9]*)

admin_event_manager_add:
    path: /admin/event/manager/add
    controller: App\Controller\administration\AdminEventManagerController::add

admin_event_manager_update:
    path: /admin/event/manager/update
    controller: App\Controller\administration\AdminEventManagerController::update

admin_event_manager_delete:
    path: /admin/event/manager/delete
    controller: App\Controller\administration\AdminEventManagerController::delete

admin_event_manager_events:
    path: /admin/event/manager/events
    controller: App\Controller\administration\AdminEventManagerController::events

admin_event_manager_update_datetime:
    path: /admin/event/manager/update/datetime
    controller: App\Controller\administration\AdminEventManagerController::updateDatetime

    #--jobs
job_add:
    path: /admin/job/add
    controller: App\Controller\JobController::add


### Errors routing ###
error_404:
    path: /error404
    controller: App\Controller\ErrorController::error404

error_403:
    path: /error403
    controller: App\Controller\ErrorController::error403

error_404_unexist_route:
    path: /{catchAll}
    defaults:
        _controller: App\Controller\ErrorController::error404
        requirements:
           catchAll: '.+'