home:
    path: /profile/Accueil
    controller: App\Controller\HomeController::index

registration:
    path: /profile/Inscription
    controller: App\Controller\RegistrationController::index


### Account routing ###
account_add:
    path: /profile/siteInscription
    controller: App\Controller\AccountController::index

account_forgot_password:
    path: /profile/forgotPassword
    controller: App\Controller\AccountController::forgotPassword

account_reset_password:
    path: /profile/resetPassword/{token}
    controller: App\Controller\AccountController::resetPassword

### Authentication routing ###
connexion_security:
    path: /profile/login
    controller: App\Controller\SecurityController::login

deconnexion_security:
    path: /profile/logout

### Administration routing ###
administration:
    path: /admin/Administration
    controller: App\Controller\AdministrationController::index

adherent_competiteurs:
    path: /admin/competiteurs
    controller: App\Controller\AdministrationController::competiteurs