home:
    path: /Accueil
    controller: App\Controller\HomeController::index

administration:
    path: /Administration
    controller: App\Controller\AdministrationController::index

registration:
    path: /Inscription
    controller: App\Controller\RegistrationController::index

register_site_index:
    path: /SiteInscription
    controller: App\Controller\AccountController::index

connexion_security:
  path: /login
  controller: App\Controller\SecurityController::login

deconnexion_security:
  path: /logout

connexion_api:
  path: /api/connexion
  controller: App\Controller\SecurityController::loginPlugin
  methods: [POST]