home:
    path: /profile/Accueil
    controller: App\Controller\HomeController::index

administration:
    path: /admin/Administration
    controller: App\Controller\AdministrationController::index

registration:
    path: /profile/Inscription
    controller: App\Controller\RegistrationController::index

register_site_index:
    path: /profile/siteInscription
    controller: App\Controller\AccountController::index

connexion_security:
  path: /profile/login
  controller: App\Controller\SecurityController::login

deconnexion_security:
  path: /profile/logout

connexion_api:
  path: /api/connexion
  controller: App\Controller\SecurityController::loginPlugin
  methods: [POST]

message_api:
  path: /api/msg
  controller: App\Controller\SecurityController::msg
  methods: [GET]