home:
    path: /profile/Accueil
    controller: App\Controller\HomeController::index

registration:
    path: /profile/Inscription
    controller: App\Controller\RegistrationController::index


### Account routing ###
account_add:
    path: /profile/siteInscription
    controller: App\Controller\AccountController::index

account_forgot_password:
    path: /profile/forgotPassword
    controller: App\Controller\AccountController::forgotPassword

account_reset_password:
    path: /profile/resetPassword/{token}
    controller: App\Controller\AccountController::resetPassword

### Authentication routing ###
security_connexion:
    path: /profile/login
    controller: App\Controller\SecurityController::login

security_deconnexion:
    path: /profile/logout

### Administration routing ###
admin_index:
    path: /admin/Administration
    controller: App\Controller\AdministrationController::index

admin_adherent_competiteurs:
    path: /admin/competiteurs
    controller: App\Controller\AdministrationController::competiteurs

### Errors routing ###
error_404:
    path: /error404
    controller: App\Controller\ErrorController::error404

error_403:
    path: /error403
    controller: App\Controller\ErrorController::error403

error_404_unexist_route:
    path: /{path}
    defaults:
        _controller: App\Controller\ErrorController::error404
        requirements:
            path: .*


