home:
    path: /profile/Accueil
    controller: App\Controller\HomeController::index

registration:
    path: /profile/Inscription
    controller: App\Controller\RegistrationController::index


### Account routing ###
account_add:
    path: /profile/siteInscription
    controller: App\Controller\AccountController::add

account_update:
    path: /profile/update
    controller: App\Controller\AccountController::update

account_forgot_password:
    path: /profile/forgotPassword
    controller: App\Controller\AccountController::forgotPassword

account_reset_password:
    path: /profile/resetPassword/{token}
    controller: App\Controller\AccountController::resetPassword

### Authentication routing ###
security_connexion:
    path: /profile/login
    controller: App\Controller\SecurityController::login

security_deconnexion:
    path: /profile/logout

### Administration routing ###
admin_adherent_competiteurs:
    path: /admin/competiteurs
    controller: App\Controller\administration\AdministrationController::competiteurs

    #--adherents
admin_adherents:
    path: /admin/adherents
    controller: App\Controller\administration\AdminAdherentsController::index

admin_adherentsEdit:
    path: /admin/adherents/edit/{id}
    controller: App\Controller\administration\AdminAdherentsController::edit
    requirements:
        id: ([0-9]*)
    
admin_adherentsRegister:
    path: /admin/adherents/register/{id}
    controller: App\Controller\administration\AdminAdherentsController::register
    requirements:
        id: ([0-9]*)

admin_adherentsDelete:
    path: /admin/adherents/delete/{id}
    controller: App\Controller\administration\AdminAdherentsController::delete
    requirements:
        id: ([0-9]*)

    #--activities
admin_activities:
    path: /admin/activities
    controller: App\Controller\administration\AdminActivitiesController::index

admin_activityAdd:
    path: /admin/activities/addActivity
    controller: App\Controller\administration\AdminActivitiesController::addActivity

admin_activityEdit:
    path: /admin/activities/editActivity/{id}
    controller: App\Controller\administration\AdminActivitiesController::editActivity

admin_activityDelete:
    path: /admin/activities/deleteActivity/{id}
    controller: App\Controller\administration\AdminActivitiesController::deleteActivity

admin_categories:
    path: /admin/categories
    controller: App\Controller\administration\AdminActivitiesController::index

admin_categoryEdit:
    path: /admin/categories/edit/{id}
    controller: App\Controller\administration\AdminActivitiesController::edit

admin_categoryAdd:
    path: /admin/categories/add
    controller: App\Controller\administration\AdminActivitiesController::add

admin_categoryDelete:
    path: /admin/categories/delete/{id}
    controller: App\Controller\administration\AdminActivitiesController::delete


    #--timeSlots
admin_timeSlots:
    path: /admin/timeSlots
    controller: App\Controller\administration\AdminTimeSlotsController::index

admin_timeSlotsEdit:
    path: /admin/timeSlots/edit/{id}
    controller: App\Controller\administration\AdminTimeSlotsController::edit
    requirements:
        id: ([0-9]*)

admin_timeSlotsDelete:
    path: /admin/timeSlots/delete/{id}
    controller: App\Controller\administration\AdminTimeSlotsController::delete
    requirements:
        id: ([0-9]*)

    #--accounts
admin_accounts:
    path: /admin/accounts
    controller: App\Controller\administration\AdminAccountsController::index

    #--events
admin_events:
    path: /admin/events
    controller: App\Controller\administration\AdminEventsController::index


### Errors routing ###
error_404:
    path: /error404
    controller: App\Controller\ErrorController::error404

error_403:
    path: /error403
    controller: App\Controller\ErrorController::error403

error_404_unexist_route:
    path: /{catchAll}
    defaults:
        _controller: App\Controller\ErrorController::error404
        requirements:
            catchAll: '.+'


